LayeredMvcProject/Controllers/AuthorizationController.cs
using Business.Concrete;
using DataAccess.EntityFramework;
using Entity.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LayeredMvcProject.Controllers
{
    public class AuthorizationController : Controller
    {
        AdminManager adminManager = new AdminManager(new EfAdminDal());
        public ActionResult Index()
        {
            var adminValues = adminManager.GetAdminList();
            return View(adminValues);
        }

        [HttpGet]
        public ActionResult AddAdmin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAdmin(Admin admin)
        {
            adminManager.AddAdmin(admin);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditAdmin(int id)
        {
            var adminValue = adminManager.GetAdminByID(id);
            return View(adminValue);
        }

        [HttpPost]
        public ActionResult EditAdmin(Admin admin)
        {
            adminManager.UpdateAdmin(admin);
            return RedirectToAction("Index");
        }
    }
}

LayeredMvcProject/Views/Authorization/AddAdmin.cshtml
@using Entity.Concrete
@model Admin

@{
    ViewBag.Title = "AddAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <h1 class="text-center">Yeni Kategori Ekleme Sayfası</h1>
    <br />
    @using (Html.BeginForm("AddAdmin", "Authorization", FormMethod.Post))
    {
        <div class="form-group">
            @Html.Label("Admin Kullanıcı Adı:")
            @Html.TextBoxFor(x => x.AdminUserName, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.AdminUserName)
            <br />
            <br />
            @Html.Label("Şifre:")
            @Html.TextBoxFor(x => x.AdminPassword, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.AdminPassword)
            <br />
            <br />
            @Html.Label("Rolü Seçiniz:")
            @Html.TextBoxFor(x => x.AdminRole, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.AdminRole)
            <br />
            <br />
            <button class="btn btn-primary">Kaydet</button>
        </div>
    }
</div>

LayeredMvcProject/Views/Authorization/EditAdmin.cshtml
@using Entity.Concrete
@model Admin

@{
    ViewBag.Title = "EditAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <h1 class="text-center">Admin Güncelleme Sayfası</h1>
    <br />
    @using (Html.BeginForm("EditAdmin", "Authorization", FormMethod.Post))
    {
        <div class="form-group">
            @Html.HiddenFor(x => x.AdminID, new { @class = "form-control" })
            @Html.Label("Admin Kullanıcı Adı:")
            @Html.TextBoxFor(x => x.AdminUserName, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.AdminUserName)
            <br />
            <br />
            @Html.Label("Şifre:")
            @Html.TextBoxFor(x => x.AdminPassword, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.AdminPassword)
            <br />
            <br />
            @Html.Label("Rol:")
            @Html.TextBoxFor(x => x.AdminRole, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.AdminRole)
            <br />
            <br />
            <button class="btn btn-primary">Güncelle</button>
        </div>
    }
</div>

LayeredMvcProject/Views/Authorization/Index.cshtml
@using Entity.Concrete
@model List<Admin>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container-fluid">
    <table class="table table-bordered">
        <tr>
            <th>#</th>
            <th>Kullanıcı Mail</th>
            <th>Yetki</th>
            <th>Status</th>
            <th>Pasif Yap</th>
            <th>Yetkisini Değiştir</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <th>@item.AdminID</th>
                <td>@item.AdminUserName</td>
                <td>@item.AdminRole</td>
                <td>Aktif</td>
                <td class="text-center"><a href="/AdminCategory/EditCategory/@item.AdminID" class="btn btn-success">Pasif Yap</a></td>
                <td class="text-center"><a href="/Authorization/EditAdmin/@item.AdminID" class="btn btn-outline-warning">Yetkisini Değiştir</a></td>
            </tr>
        }
    </table>
    <a href="/Authorization/AddAdmin" class="btn btn-primary">Yeni Admin Tanımla</a>
</div>